### ISSUE TITLE
Feature Request add Guest support

### ISSUE THREAD

**Issue by Dronax** [artisanry/commentable#49]
Hello. I suggest add to this package:

- Guest support, when add comment, user writes a email, and when user submit a comment, email must be verified, system send a email with confirmation on email user, and after confirmation comment will be published.
- Add like/dislike comment
- Add a type_comment (Good, Negative, Normal)
- Add child comments (how on facebook)

**Comment by nguyentranchung** [comment]
@Dronax 
"Add child comments (how on facebook)" this feature supported

**Comment by faustbrian** [comment]
Child comments are already supported, for the rest there currently are no plans but feel free to submit a PR.
